dev:
	@ nix develop --ignore-environment \
		--keep HOME \
		--keep TERM \
		--keep COLORTERM \
		--keep TERM_PROGRAM \
		--keep TERM_PROGRAM \
		--keep TERM_PROGRAM_VERSION \
		-c zsh -o zle -o promptsubst -o interactive -o monitor
